name: Replace urls

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  replace-urls:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Revert proxy URLs back to original
      run: |
        find . -type f -exec sed -i 's|https://proxy.muuua.cn/proxy/https://raw.githubusercontent.com/|https://raw.githubusercontent.com/|g' {} +

    - name: Replace original URLs with proxy
      run: |
        find . -type f -exec sed -i 's|https://raw.githubusercontent.com/|https://proxy.muuua.cn/proxy/https://raw.githubusercontent.com/|g' {} +

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add -A
        git commit -m 'Replace raw.githubusercontent.com URLs with proxy'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
