name: Replace urls

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  replace-urls:
    runs-on: ubuntu-latest
    permissions:                # Job-level permissions configuration starts here
      contents: write           # 'write' access to repository contents
      pull-requests: write      # 'write' access to pull requests
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Revert proxy URLs back to original
      run: |
        find . -type f -exec sed -i 's|https://proxy.muuua.cn/proxy/https://raw.githubusercontent.com/|https://raw.githubusercontent.com/|g' {} +

    - name: Replace original URLs with proxy
      run: |
        find . -type f -exec sed -i 's|https://raw.githubusercontent.com/|https://proxy.muuua.cn/proxy/https://raw.githubusercontent.com/|g' {} +

    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -a -m "replace urls"
    - name: GitHub Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAT }}
